# Generated by Django 3.1.1 on 2020-09-14 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Порода')),
                ('breed_description', models.TextField(verbose_name='Описание породы')),
                ('code', models.CharField(max_length=128, verbose_name='Код для поиска')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_num', models.CharField(auto_created=True, blank=True, max_length=256, null=True, verbose_name='Номер документа')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата регистрации')),
                ('cage', models.CharField(max_length=10, verbose_name='Номер клетки')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Кличка')),
                ('story', models.TextField(verbose_name='История кошки')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('color', models.CharField(choices=[('BL', 'Black'), ('GR', 'Grey'), ('WH', 'White'), ('RD', 'Redhead')], max_length=2, verbose_name='Цвет')),
                ('mood', models.CharField(max_length=128, verbose_name='Настроение кошки')),
                ('photo', models.ImageField(blank=True, upload_to='media/pets_photo', verbose_name='Фото')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_breed', to='pet.breed', verbose_name='Порода')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_doc', to='pet.registration', verbose_name='Регистрационный документ')),
                ('food', models.ManyToManyField(related_name='pet_food', to='pet.Food', verbose_name='Любимое лакомство')),
            ],
        ),
    ]
